# Generated by Django 3.1.3 on 2020-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201202_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_world',
            new_name='fess_in_world',
        ),
        migrations.RenameField(
            model_name='movieshots',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.SmallIntegerField(default=0, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Сообщение'),
        ),
    ]
